"""End-to-end projection reconciliation across mncs-automation and mncs-doc.

A canonical generation advances, the native reconcile tick marks the
projection stale, mncs-doc applies regenerated bytes to the document's
machine-owned region, adoption advances the observed generation, and a
second tick converges without duplicating work. Verification verdicts
gate authoritative claims; interruption recovers without duplicates;
stale generations never overwrite newer output.

Time is injected everywhere; no test touches the network or the real
clock. Skipped cleanly when the compiler binary or the sibling
mncs-doc checkout is absent.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(REPO / "tools"))

from automation import codes, native  # noqa: E402

WORKSPACE = REPO.parent
DOC_REPO = WORKSPACE / "mncs-doc"
PROJECT_CLI = DOC_REPO / "tools" / "project.py"
STORE_RECEIPT = (WORKSPACE / "mncs-store" / "src" / "store"
                 / "receipt.mncs")


def find_mncs() -> str | None:
    for candidate in (
        os.environ.get("MNCS_BIN"),
        os.environ.get("MNCS_BINARY"),
        str(WORKSPACE / "mncs-language" / "target" / "debug" / "mncs"),
    ):
        if candidate and Path(candidate).is_file():
            return candidate
    return None


MNCS = find_mncs()
LIBRARIES = [str(WORKSPACE / "mncs-test" / "native"),
             str(REPO / "native")]


def need_mncs(test):
    return unittest.skipIf(MNCS is None, "mncs binary unavailable")(test)


def need_doc(test):
    return unittest.skipIf(not PROJECT_CLI.is_file(),
                           "mncs-doc projection CLI unavailable")(test)


def need_store_receipt(test):
    return unittest.skipIf(not STORE_RECEIPT.is_file(),
                           "mncs-store receipt module unavailable")(test)


def tick(**fields: Any) -> dict[str, Any]:
    base = {"canonical_gen": 5, "observed_gen": 5,
            "verdict": codes.VERDICT_PASS, "require_verified": 1,
            "unpublished": 0, "threshold": 0,
            "oldest_unpublished_ms": 0, "now_ms": 9_000,
            "max_latency_ms": 0}
    base.update(fields)
    assert MNCS is not None
    return native.reconcile_tick(mncs=MNCS, libraries=LIBRARIES, **base)


def adopt(observed: int, regenerated: int, canonical: int) -> dict[str, Any]:
    assert MNCS is not None
    return native.adopt_observed(
        mncs=MNCS, libraries=LIBRARIES, observed_gen=observed,
        regenerated_gen=regenerated, canonical_gen=canonical)


class ReconcileCase(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="reconcile-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.document = self.tmp / "README.md"
        self.generated = self.tmp / "generated.md"
        self.receipts = self.tmp / "receipts.jsonl"

    def write_fixture(self, region_body: str, prose_head: str = "# Title\n\n",
                      prose_tail: str = "\nHuman outro.\n") -> None:
        self.document.write_text(
            f"{prose_head}<!-- MNCS:generated:begin -->\n{region_body}\n"
            f"<!-- MNCS:generated:end -->{prose_tail}", encoding="utf-8")

    def apply(self, body: str, check: bool = False,
              create: bool = False) -> bool:
        self.generated.write_text(body, encoding="utf-8")
        assert MNCS is not None
        command = [sys.executable, str(PROJECT_CLI), "project-apply",
                   "--document", str(self.document),
                   "--generated", str(self.generated),
                   "--sources", "2", "--template-present", "1",
                   "--mncs-bin", MNCS]
        if create:
            command.append("--create")
        if check:
            command.append("--check")
        completed = subprocess.run(command, capture_output=True, text=True,
                                   timeout=180)
        return completed.returncode == 0

    def record_receipt(self, key: tuple[str, str, str],
                       generation: int) -> bool:
        """Append a receipt unless this publication key already has one."""
        existing = set()
        if self.receipts.exists():
            for line in self.receipts.read_text(encoding="utf-8").splitlines():
                entry = json.loads(line)
                existing.add((entry["artifact"], entry["target"],
                              entry["external"]))
        if key in existing:
            return False
        with self.receipts.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps({"artifact": key[0], "target": key[1],
                                     "external": key[2],
                                     "canonical_generation": generation,
                                     "schema_version":
                                     "mncs.publication-receipt/1"}) + "\n")
        return True


class NativeReconcileCodeTests(unittest.TestCase):
    @need_mncs
    def test_codes_match_native(self) -> None:
        program = str(REPO / "native" / "mncs" / "automation"
                      / "reconcile.mncs")
        module = "mncs.automation.reconcile.v1"

        def call(function: str, args: list) -> Any:
            assert MNCS is not None
            document = native.call_function(
                mncs=MNCS, program=program, module=module,
                function=function, args=args, libraries=LIBRARIES)
            return document["call"]["returned"][0]["integer"]["value"]

        for function, expected in (
                ("verdict_fail", codes.VERDICT_FAIL),
                ("verdict_pass", codes.VERDICT_PASS),
                ("verdict_unknown", codes.VERDICT_UNKNOWN)):
            self.assertEqual(call(function, []), expected)
        for variant, expected in (
                ("UpToDate", codes.RECON_UP_TO_DATE),
                ("Regenerate", codes.RECON_REGENERATE),
                ("AwaitVerification", codes.RECON_AWAIT_VERIFICATION),
                ("Blocked", codes.RECON_BLOCKED),
                ("FailedVerification", codes.RECON_FAILED_VERIFICATION)):
            self.assertEqual(
                call("action_code", [{"finite": {"type": "ReconAction",
                                                "variant": variant}}]),
                expected)
        for variant, expected in (
                ("Current", codes.RECON_REASON_CURRENT),
                ("CanonicalAdvanced",
                 codes.RECON_REASON_CANONICAL_ADVANCED),
                ("VerificationUnknown",
                 codes.RECON_REASON_VERIFICATION_UNKNOWN),
                ("VerificationFailed",
                 codes.RECON_REASON_VERIFICATION_FAILED),
                ("ObservedAhead", codes.RECON_REASON_OBSERVED_AHEAD)):
            self.assertEqual(
                call("reason_code", [{"finite": {"type": "ReconReason",
                                                "variant": variant}}]),
                expected)


class NativeProjectionPlanTests(unittest.TestCase):
    @need_mncs
    def test_gate_codes_match_native(self) -> None:
        program = str(REPO / "native" / "mncs" / "automation"
                      / "projection.mncs")
        module = "mncs.automation.projection.v1"

        def call(function: str, args: list) -> Any:
            assert MNCS is not None
            document = native.call_function(
                mncs=MNCS, program=program, module=module,
                function=function, args=args, libraries=LIBRARIES)
            return document["call"]["returned"][0]["integer"]["value"]

        for variant, expected in (
                ("Proceed", codes.GATE_PROCEED),
                ("Defer", codes.GATE_DEFER),
                ("Escalate", codes.GATE_ESCALATE)):
            self.assertEqual(
                call("gate_code", [{"finite": {"type": "Gate",
                                               "variant": variant}}]),
                expected)
        for variant, expected in (
                ("Ok", codes.GATE_REASON_OK),
                ("DeferredForeignClaim",
                 codes.GATE_REASON_FOREIGN_CLAIM),
                ("DeferredForeignMutation",
                 codes.GATE_REASON_FOREIGN_MUTATION),
                ("DeferredForeignBranch",
                 codes.GATE_REASON_FOREIGN_BRANCH),
                ("DeferredAmbiguous", codes.GATE_REASON_AMBIGUOUS),
                ("DeferredRegionExplicitOnly",
                 codes.GATE_REASON_REGION_EXPLICIT_ONLY),
                ("EscalateAmbiguousMarkers",
                 codes.GATE_REASON_AMBIGUOUS_MARKERS),
                ("EscalateUnknownTarget",
                 codes.GATE_REASON_UNKNOWN_TARGET),
                ("EscalateHumanOnly", codes.GATE_REASON_HUMAN_ONLY),
                ("EscalateUnknownRepo",
                 codes.GATE_REASON_UNKNOWN_REPO),
                ("DeferredOutputDiverged",
                 codes.GATE_REASON_OUTPUT_DIVERGED),
                ("EscalateDeferralExhausted",
                 codes.GATE_REASON_DEFERRAL_EXHAUSTED)):
            self.assertEqual(
                call("gate_reason_code", [{"finite": {"type": "GateReason",
                                                      "variant": variant}}]),
                expected)

    @need_mncs
    def test_plan_bridge_defers_foreign_claim(self) -> None:
        assert MNCS is not None
        plan = native.plan_tick(
            mncs=MNCS, libraries=LIBRARIES, canonical_gen=5,
            observed_gen=4, inputs_changed=0, verdict=codes.VERDICT_PASS,
            require_verified=1, repo=codes.REPO_CLEAN,
            branch=codes.BRANCH_MAINLINE, claim=codes.CLAIM_FOREIGN,
            target=codes.TARGET_WHOLE_FILE,
            region=codes.REGION_NOT_APPLICABLE,
            output=codes.OUTPUT_MISSING, splice_ok=0, defer_count=0,
            defer_bound=0, unpublished=0, threshold=0,
            oldest_unpublished_ms=0, now_ms=9_000, max_latency_ms=0)
        self.assertEqual(plan["gate"], codes.GATE_DEFER)
        self.assertEqual(plan["gate_reason"],
                         codes.GATE_REASON_FOREIGN_CLAIM)
        self.assertEqual(plan["action"], codes.RECON_REGENERATE)
        self.assertFalse(plan["execute"])

    @need_mncs
    def test_reconcile_cli_prints_plan_envelope(self) -> None:
        request = {"projection": "test:plan",
                   "canonical_gen": 5, "observed_gen": 4,
                   "inputs_changed": 0, "verdict": codes.VERDICT_PASS,
                   "require_verified": 1, "repo": codes.REPO_CLEAN,
                   "branch": codes.BRANCH_MAINLINE,
                   "claim": codes.CLAIM_NONE,
                   "target": codes.TARGET_WHOLE_FILE,
                   "region": codes.REGION_NOT_APPLICABLE,
                   "output": codes.OUTPUT_MISSING, "splice_ok": 0,
                   "defer_count": 0, "defer_bound": 0, "unpublished": 0,
                   "threshold": 0, "oldest_unpublished_ms": 0,
                   "now_ms": 9_000, "max_latency_ms": 0}
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as handle:
            json.dump(request, handle)
            path = handle.name
        try:
            assert MNCS is not None
            completed = subprocess.run(
                [sys.executable, str(REPO / "tools" / "reconcile.py"),
                 "plan", "--request", path, "--mncs", MNCS],
                capture_output=True, text=True, timeout=180)
        finally:
            os.unlink(path)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        envelope = json.loads(completed.stdout)
        self.assertEqual(envelope["schema_version"], codes.PLAN_SCHEMA)
        self.assertEqual(envelope["projection"], "test:plan")
        self.assertTrue(envelope["execute"])
        self.assertEqual(envelope["gate_name"], "proceed")

    @need_mncs
    def test_reconcile_cli_rejects_bad_request(self) -> None:
        with tempfile.NamedTemporaryFile("w", suffix=".json",
                                         delete=False) as handle:
            json.dump({"projection": "test:bad"}, handle)
            path = handle.name
        try:
            assert MNCS is not None
            completed = subprocess.run(
                [sys.executable, str(REPO / "tools" / "reconcile.py"),
                 "plan", "--request", path, "--mncs", MNCS],
                capture_output=True, text=True, timeout=180)
        finally:
            os.unlink(path)
        self.assertEqual(completed.returncode, 2)
        self.assertEqual(completed.stdout, "")


class DogfoodIndexTests(unittest.TestCase):
    @need_doc
    def test_own_rfc_index_is_current(self) -> None:
        completed = subprocess.run(
            [sys.executable, str(PROJECT_CLI), "project-rfc-index",
             "--rfc-root", str(REPO / "docs" / "rfcs"),
             "--output", str(REPO / "docs" / "rfc-index.generated.md"),
             "--check"],
            capture_output=True, text=True, timeout=120)
        self.assertEqual(completed.returncode, 0, completed.stderr)


class ReconcileFlowTests(ReconcileCase):
    @need_mncs
    @need_doc
    def test_stale_regenerates_then_converges(self) -> None:
        self.write_fixture("generation 4 status")
        first = tick(canonical_gen=5, observed_gen=4)
        self.assertEqual(first["action"], codes.RECON_REGENERATE)
        self.assertTrue(self.apply("generation 5 status"))
        rendered = self.document.read_text(encoding="utf-8")
        self.assertIn("generation 5 status", rendered)

        adopted = adopt(observed=4, regenerated=5, canonical=5)
        self.assertTrue(adopted["accept"])
        self.assertEqual(adopted["new_observed"], 5)

        second = tick(canonical_gen=5, observed_gen=adopted["new_observed"])
        self.assertEqual(second["action"], codes.RECON_UP_TO_DATE)
        before = self.document.read_bytes()
        self.assertTrue(self.apply("generation 5 status", check=True))
        self.assertEqual(before, self.document.read_bytes())

    @need_mncs
    @need_doc
    def test_failed_verification_withholds_regeneration(self) -> None:
        self.write_fixture("generation 4 status")
        decision = tick(canonical_gen=6, observed_gen=4,
                        verdict=codes.VERDICT_FAIL)
        self.assertEqual(decision["action"],
                         codes.RECON_FAILED_VERIFICATION)
        self.assertFalse(decision["publish"])
        # The reconciler performs no regeneration while gated.
        self.assertIn("generation 4 status",
                      self.document.read_text(encoding="utf-8"))
        released = tick(canonical_gen=6, observed_gen=4,
                        verdict=codes.VERDICT_PASS)
        self.assertEqual(released["action"], codes.RECON_REGENERATE)

    @need_mncs
    @need_doc
    def test_duplicate_event_regenerates_once(self) -> None:
        self.write_fixture("generation 4 status")
        first = tick(canonical_gen=5, observed_gen=4)
        self.assertEqual(first["action"], codes.RECON_REGENERATE)
        self.assertTrue(self.apply("generation 5 status"))
        adopted = adopt(observed=4, regenerated=5, canonical=5)
        settled = self.document.read_bytes()
        # The same canonical event observed again changes nothing.
        replay = tick(canonical_gen=5, observed_gen=adopted["new_observed"])
        self.assertEqual(replay["action"], codes.RECON_UP_TO_DATE)
        self.assertEqual(settled, self.document.read_bytes())

    @need_mncs
    @need_doc
    def test_interrupted_regeneration_recovers_without_duplicates(self) -> None:
        self.write_fixture("generation 5 status")
        before_crash = tick(canonical_gen=6, observed_gen=5)
        self.assertEqual(before_crash["action"], codes.RECON_REGENERATE)
        # Crash after regenerating but before adopting: bytes are
        # rewritten deterministically and observed never advances.
        self.assertTrue(self.apply("generation 6 status"))
        after_restart = tick(canonical_gen=6, observed_gen=5)
        self.assertEqual(after_restart["action"], codes.RECON_REGENERATE)
        self.assertTrue(self.apply("generation 6 status"))
        adopted = adopt(observed=5, regenerated=6, canonical=6)
        self.assertTrue(adopted["accept"])
        converged = tick(canonical_gen=6,
                         observed_gen=adopted["new_observed"])
        self.assertEqual(converged["action"], codes.RECON_UP_TO_DATE)
        # A stale regeneration replayed after convergence is refused.
        stale = adopt(observed=6, regenerated=5, canonical=6)
        self.assertFalse(stale["accept"])
        self.assertEqual(stale["reason"], codes.RECON_ADOPT_REGRESSION)
        self.assertEqual(stale["new_observed"], 6)

    @need_mncs
    def test_observed_ahead_blocks_without_publish(self) -> None:
        decision = tick(canonical_gen=5, observed_gen=6, unpublished=9,
                        threshold=3, oldest_unpublished_ms=1_000,
                        now_ms=9_000, max_latency_ms=1_000)
        self.assertEqual(decision["action"], codes.RECON_BLOCKED)
        self.assertEqual(decision["reason"],
                         codes.RECON_REASON_OBSERVED_AHEAD)
        self.assertFalse(decision["publish"])

    @need_mncs
    @need_doc
    def test_human_prose_regions_remain_untouched(self) -> None:
        head = "# Titre — with unicode déjà ✓\n\nFirst § paragraph.\n\n"
        tail = "\nLast ¶ paragraph — fin.\n"
        self.write_fixture("old", prose_head=head, prose_tail=tail)
        decision = tick(canonical_gen=5, observed_gen=4)
        self.assertEqual(decision["action"], codes.RECON_REGENERATE)
        self.assertTrue(self.apply("new"))
        rendered = self.document.read_text(encoding="utf-8")
        self.assertTrue(rendered.startswith(head))
        self.assertTrue(rendered.endswith(tail))
        self.assertIn("\nnew\n", rendered)

    @need_mncs
    def test_publish_threshold_fires_once_per_receipt(self) -> None:
        key = ("sha256:artifact", "target:mock", "external:1")
        decision = tick(canonical_gen=5, observed_gen=5, unpublished=3,
                        threshold=3)
        self.assertTrue(decision["publish"])
        self.assertTrue(self.record_receipt(key, 5))
        # The duplicate publication event finds the receipt and writes
        # nothing; with nothing unpublished the tick goes quiet.
        self.assertFalse(self.record_receipt(key, 5))
        quiet = tick(canonical_gen=5, observed_gen=5, unpublished=0,
                     threshold=3)
        self.assertFalse(quiet["publish"])
        lines = self.receipts.read_text(encoding="utf-8").splitlines()
        self.assertEqual(len(lines), 1)

    @need_mncs
    @need_store_receipt
    def test_receipt_identity_is_the_dedup_key(self) -> None:
        def receipt(artifact: int, target: int, external: int,
                    generation: int, evidence: int) -> list[int]:
            out = [80, 82, 1, 0] + [artifact] * 32 + [target] * 32
            out += [external] * 32
            out += [(generation >> shift) & 0xFF
                    for shift in (56, 48, 40, 32, 24, 16, 8, 0)]
            return out + [evidence] * 32

        def same(left: list[int], right: list[int]) -> bool:
            assert MNCS is not None
            document = native.call_function(
                mncs=MNCS, program=str(STORE_RECEIPT),
                module="store.receipt.v1", function="same_publication",
                args=[{"sequence": {"values": [{"byte": {"value": v}}
                                                    for v in left]}},
                      {"sequence": {"values": [{"byte": {"value": v}}
                                                    for v in right]}}],
                libraries=LIBRARIES)
            return bool(document["call"]["returned"][0]["boolean"]["value"])

        original = receipt(11, 12, 13, 7, 14)
        rerecorded = receipt(11, 12, 13, 9, 15)
        other = receipt(11, 12, 16, 7, 14)
        self.assertTrue(same(original, rerecorded))
        self.assertFalse(same(original, other))


if __name__ == "__main__":
    unittest.main()
